main/urls.py
from django.urls import path
from . import views as main

app_name = 'main'

urlpatterns = [
    path('', main.index, name='index'),
    path('profile/<int:pk>/', main.profile, name='profile'),
    path('calendar/', main.calendar, name='calendar'),
    path('api/parse_results/', main.ajax_parse_results),
    path('goals/', main.goals, name='goals'),
    path('leadership/', main.leadership, name='leadership'),
    path('documents/', main.documents, name='documents'),
    path('protocols/', main.protocols, name='protocols'),
    path('regulations/', main.regulations, name='regulations'),
    path('studentsTournaments/', main.students_tournaments, name='students_tournaments'),
    path('contacts/', main.contacts, name='contacts'),
    path('payment/', main.payment, name='payment'),
    path('api/calendar/', main.CalendarApiView.as_view()),
]

news/urls.py
from django.urls import path
from .views import news_list, current_news

app_name = 'news'

urlpatterns = [
    path('news/', news_list, name='news_list'),
    path('news/<int:pk>/', current_news, name='current_news'),
]

rating/urls.py
from django.urls import path
from .views import statistic, rating, upload_rating_ajax

app_name = 'rating'

urlpatterns = [
    path('statistic/', statistic, name='statistic'),
    path('rating/', rating, name='rating'),
    path('uploadRating/', upload_rating_ajax),
]

tournaments/urls.py
from django.urls import path
from .views import tournaments_list, current_tournament, results

app_name = 'tournaments'

urlpatterns = [
    path('tournaments/', tournaments_list, name='tournaments_list'),
    path('tournaments/<int:pk>/', current_tournament, name='current_tournament'),
    path('results/', results, name='results'),
]

rating/models.py
from django.db import models
from main.models import Profile
from tournaments.models import Years


class Rating(models.Model):
    LEAGUE = (
        ('men', 'Мужчины'),
        ('women', 'Женщины'),
    )
    player = models.OneToOneField(Profile, verbose_name='Спортсмен', on_delete=models.PROTECT)
    score = models.SmallIntegerField(verbose_name='Очки')
    league = models.TextField(choices=LEAGUE, verbose_name='Лига')

    def __str__(self):
        return self.player.name

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинг топ 8'
        ordering = ['league', '-score']


class AllRating(models.Model):
    year = models.ForeignKey(Years, on_delete=models.PROTECT, verbose_name='Год', null=True, blank=True,
                             related_name='rating_year')
    SEX = (
        ('men', 'Мужчины'),
        ('women', 'Женщины'),
    )
    sex = models.CharField(max_length=5, verbose_name='Пол', choices=SEX, default='men')
    rating = models.TextField(verbose_name='Райтинг Json')

    def __str__(self):
        return f'Райтинг {self.year.year}года - {self.get_sex_display()}'

    class Meta:
        verbose_name = 'Полный рейтинг'
        verbose_name_plural = 'Полный рейтинг (для страницы рейтинг)'
        ordering = ['year']


class Statistics(models.Model):
    name = models.ForeignKey(Profile, related_name='statistic_profile', on_delete=models.PROTECT,
                             verbose_name='Спортсмен')
    year = models.ForeignKey(Years, on_delete=models.PROTECT, verbose_name='Год', null=True, blank=True,
                             related_name='statistic_year')
    SEX = (
        ('men', 'М'),
        ('women', 'Ж'),
    )
    sex = models.CharField(max_length=5, verbose_name='Пол', choices=SEX, default='men')
    mean = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Средний', default=0)
    min = models.SmallIntegerField(verbose_name='Минимальная игра', default=300)
    max = models.SmallIntegerField(verbose_name='Максимальная игра', default=0)
    score = models.SmallIntegerField(verbose_name='Количество игр', default=0)
    games_more_200 = models.SmallIntegerField(verbose_name='Количество игр за 200', default=0)
    mean_games_more_200 = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Игр за 200 (процент)',
                                              default=0)
    summ = models.SmallIntegerField(verbose_name='Сумма', default=0)

    def __str__(self):
        return self.name.name

    class Meta:
        verbose_name = 'Статистику'
        verbose_name_plural = 'Персональная статистика игрока'
        ordering = ['year', '-mean']

rating/views.py
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
import json

from django.shortcuts import render
from tournaments.models import Years
from rating.models import AllRating, Rating
from main.models import Profile


def statistic(request):
    context = {
        'years': []
    }
    years = Years.objects.all()
    for year_item in years:
        year = {
            'year': year_item.year,
            'men': year_item.statistic_year.filter(sex='men'),
            'women': year_item.statistic_year.filter(sex='women'),
            'rating': year_item.rating,
        }
        context['years'].append(year)
    return render(request, 'statistics.html', context)


def rating(request):
    context = {
        'years': []
    }
    years = Years.objects.all()
    for year_item in years:
        if not year_item.rating_year.all():
            continue
        man_rating = year_item.rating_year.get(sex='men').rating
        man_rating = json.loads(man_rating)
        woman_rating = year_item.rating_year.get(sex='women').rating
        woman_rating = json.loads(woman_rating)
        year = {
            'man_rating': man_rating['data'],
            'woman_rating': woman_rating['data'],
            'year': year_item.year,
            'rating': year_item.rating
        }
        context['years'].append(year)
    return render(request, 'rating.html', context)


@csrf_exempt
def upload_rating_ajax(request):
    data = json.loads(request.body)
    year = Years.objects.get(year=data['year'])
    rating, _ = AllRating.objects.get_or_create(year=year, sex=data['sex'])
    rating.rating = json.dumps(data, ensure_ascii=False)
    rating.save()
    single_rating = Rating.objects.filter(league=data['sex'])
    for item in single_rating:
        item.delete()
    for item in data['data'][1:9]:
        try:
            player = Profile.objects.get(name=item[1])
        except ObjectDoesNotExist:
            return JsonResponse(status=400, data={
                'status': 'error',
                'message': f'player: {item[1]} has not been found'
            }, json_dumps_params={'ensure_ascii': False})
        Rating.objects.create(player=player, score=item[-1], league=data['sex'])
    return JsonResponse({
        'status': 'OK',
    })

templates/calendar.html
{% extends 'layouts/basic.html' %}
{% load static %}
{% block links %}
    <link href="/static/css/2.786ae0dd.chunk.css" rel="stylesheet">
    <link href="/static/css/main.06949941.chunk.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/calendar_1.css' %}">
{% endblock %}
{% block title %}Календарь{% endblock %}

{% block content %}
    <section class="calendar_section">
        <div class="container">
            <div id="root"></div>
            <div class="document">
                <img src="{% static 'img/pdf_icon.png' %}" alt="">
                <a href="{% static 'documents/Kalendar_SPb20220804.pdf' %}" target="_blank">Календарь PDF</a>
            </div>
        </div>
    </section>
{% endblock %}

{% block scripts %}
    <script>!function (e) {
        function r(r) {
            for (var n, l, a = r[0], f = r[1], p = r[2], c = 0, s = []; c < a.length; c++) l = a[c], Object.prototype.hasOwnProperty.call(o, l) && o[l] && s.push(o[l][0]), o[l] = 0;
            for (n in f) Object.prototype.hasOwnProperty.call(f, n) && (e[n] = f[n]);
            for (i && i(r); s.length;) s.shift()();
            return u.push.apply(u, p || []), t()
        }

        function t() {
            for (var e, r = 0; r < u.length; r++) {
                for (var t = u[r], n = !0, a = 1; a < t.length; a++) {
                    var f = t[a];
                    0 !== o[f] && (n = !1)
                }
                n && (u.splice(r--, 1), e = l(l.s = t[0]))
            }
            return e
        }

        var n = {}, o = {1: 0}, u = [];

        function l(r) {
            if (n[r]) return n[r].exports;
            var t = n[r] = {i: r, l: !1, exports: {}};
            return e[r].call(t.exports, t, t.exports, l), t.l = !0, t.exports
        }

        l.m = e, l.c = n, l.d = function (e, r, t) {
            l.o(e, r) || Object.defineProperty(e, r, {enumerable: !0, get: t})
        }, l.r = function (e) {
            "undefined" != typeof Symbol && Symbol.toStringTag && Object.defineProperty(e, Symbol.toStringTag, {value: "Module"}), Object.defineProperty(e, "__esModule", {value: !0})
        }, l.t = function (e, r) {
            if (1 & r && (e = l(e)), 8 & r) return e;
            if (4 & r && "object" == typeof e && e && e.__esModule) return e;
            var t = Object.create(null);
            if (l.r(t), Object.defineProperty(t, "default", {
                enumerable: !0,
                value: e
            }), 2 & r && "string" != typeof e) for (var n in e) l.d(t, n, function (r) {
                return e[r]
            }.bind(null, n));
            return t
        }, l.n = function (e) {
            var r = e && e.__esModule ? function () {
                return e.default
            } : function () {
                return e
            };
            return l.d(r, "a", r), r
        }, l.o = function (e, r) {
            return Object.prototype.hasOwnProperty.call(e, r)
        }, l.p = "/";
        var a = this.webpackJsonpfbspb_calendar = this.webpackJsonpfbspb_calendar || [], f = a.push.bind(a);
        a.push = r, a = a.slice();
        for (var p = 0; p < a.length; p++) r(a[p]);
        var i = f;
        t()
    }([])</script>
    <script src="/static/js/2.9c45302a.chunk.js"></script>
    <script src="/static/js/main.cb931bc0.chunk.js"></script>
{% endblock %}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style_9.css' %}">
    <link rel="stylesheet" href="{% static 'css/layouts_3.css' %}">
    <link rel="icon" href="{% static 'img/logo.png' %}">
    <meta name="viewport" content="width=450, initial-scale=0.8">
    <title>Федерация Боулинга Санкт-Петербурга</title>
</head>
<body>
<div class="background"></div>
<header>
    <div class="container">
        <div class="header">
            <div class="logo">
                <a href="{% url 'main:index' %}"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
            </div>
            <div class="nav_bar">
                <nav>
                    <div class="nav_link">
                        <a href="{% url 'news:news_list' %}">Новости</a>
                    </div>
                    <div class="nav_link">
                        <a href="#">Федерация</a>
                        <div class="accordion">
                            <a href="{% url 'main:goals' %}">Цели и задачи</a>
                            <a href="{% url 'main:leadership' %}">Руководство</a>
                            <a href="{% url 'main:documents' %}">Документы</a>
                            <a href="{% url 'main:protocols' %}">Протоколы</a>
                        </div>
                    </div>
                    <div class="nav_link">
                        <a href="#">Турниры</a>
                        <div class="accordion">
                            <a href="{% url 'main:regulations' %}">Регламенты</a>
                            <a href="{% url 'tournaments:tournaments_list' %}">Отчеты</a>
                            <a href="{% url 'tournaments:results' %}">Результаты</a>
                            <a href="{% url 'rating:statistic' %}">Статистика</a>
                            <a href="{% url 'main:students_tournaments' %}">Студенческие турниры</a>
                            <a href="{% url 'main:payment' %}">Оплата</a>
                        </div>
                    </div>
                    <div class="nav_link">
                        <a href="{% url 'main:calendar' %}">Календарь</a>
                    </div>
                    <div class="nav_link">
                        <a href="{% url 'main:contacts' %}">Контакты</a>
                    </div>
                </nav>
            </div>
            <div class="burger">
                <span></span>
            </div>
        </div>
    </div>
    <div class="main">
        <h1>Федерация Боулинга<br>Санкт-Петербурга</h1>
        <video id="video" autoplay="autoplay" muted="muted" loop>
            <source src="http://90.156.129.4/static/video/out/master.m3u8" type="application/x-mpegurl">
        </video>
    </div>
    <div class="social">
        <a href="https://vk.com/fbpiter" target="_blank">
            <img src="{% static 'img/vk.png' %}" alt="vk">
        </a>
        <a href="https://www.youtube.com/channel/UCJFdDmkmpM81jgTCgCDGUwQ" target="_blank">
            <img src="{% static 'img/youTube.png' %}" alt="youtube">
        </a>
    </div>
    <div class="angel">
        <img src="{% static 'img/bottom_angle.png' %}" alt="decoration">
    </div>
</header>

<section class="news_section">
    <div class="container">
        <div class="news_title">Последние новости</div>
        <div class="news_cards">
            {% for post in news %}
                <figure class="baha1493">
                    <div {% if not post.news_image %}style="align-items: center;"{% endif %}
                         class="image">
                        {% if post.news_image %}
                            <img src="{{ post.news_image.url }}" alt="ls-sample1"/>
                        {% else %}
                            <img style="width: unset; object-fit: unset" width="100px" height="115px" src="{% static 'img/logo.png' %}" alt="">
                        {% endif %}
                    </div>
                    <figcaption>
                        <div class="date">
                            <span class="day">{{ post.date|date:'j' }}</span>
                            <span class="month_news">{{ post.date|date:'M' }}</span>
                        </div>
                        <h3>{{ post.name }}</h3>
                        <p>{{ post.short_description }}</p>
                        <div class="news_footer">
                            <div class="views"><i class="ion-eye"></i>{{ post.count }}</div>
                        </div>
                    </figcaption>
                    <a href="{% url 'news:current_news' pk=post.pk %}"></a>
                </figure>
            {% endfor %}
        </div>
        <div class="news_button">
            <a href="{% url 'news:news_list' %}">Все новости</a>
        </div>
    </div>
</section>

<a name="calendar"></a>
<section class="calendar_section">
    <div class="container">
        <div class="calendar_block">
            <div class="calendar_title">Календарь соревнований</div>
            <div class="calendar_month">
                <p class="month" href="#">{{ current_month }}</p>
                <div class="arrow-8"></div>
                <div style="display: none" class="month_list">
                    {% for month in month_list %}
                        <a href="{% url 'main:index' %}?month={{ forloop.counter }}#calendar">{{ month }}</a>
                    {% endfor %}
                </div>
            </div>
            <div class="calendar_table">
                <table>
                    <thead>
                    <tr>
                        <th>№</th>
                        <th>Соревнование</th>
                        <th>Город</th>
                        <th>Статус</th>
                        <th>Дата начала</th>
                        <th>Дата окончания</th>
                        <th>Положение</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if not is_tournament and nearest_tournament %}
                        <tr style="background-color: #caf6f0;">
                            <td>*</td>
                            <td>{{ nearest_tournament.competition }}</td>
                            <td>{{ nearest_tournament.city }}</td>
                            <td>{{ nearest_tournament.status }}</td>
                            <td>{{ nearest_tournament.date_start|date:'d.m' }}</td>
                            <td>{{ nearest_tournament.date_finish|date:'d.m' }}</td>
                            <td>
                                {% if nearest_tournament.regulation %}
                                    <a href="{{ nearest_tournament.regulation.file.url }}"><img
                                            src="{% static 'img/file_icon.png' %}"
                                            alt="rules"></a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endif %}
                    {% for event in calendar %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ event.competition }}</td>
                            <td>{{ event.city }}</td>
                            <td>{{ event.status }}</td>
                            <td>{{ event.date_start|date:'d.m' }}</td>
                            <td>{{ event.date_finish|date:'d.m' }}</td>
                            <td>
                                {% if event.regulation %}
                                    <a href="{{ event.regulation.file.url }}"><img
                                            src="{% static 'img/file_icon.png' %}"
                                            alt="rules"></a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="calendar_button">
                <a href="{% url 'main:calendar' %}">Весь календарь</a>
            </div>
        </div>
    </div>
</section>

<section class="rating_section">
    <div class="container">
        <div class="rating_title">Рейтинг спортсменов</div>
        <div class="rating_tables">
            <div class="rating_man">
                <h3>Мужчины</h3>
                <table>
                    <thead>
                    <tr style="background-color: #009688;">
                        <th>Место</th>
                        <th>Разряд</th>
                        <th>Спортсмен</th>
                        <th>Очки</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for player in man %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            {% if not player.player.rang == 'nan' %}
                                <td>{{ player.player.rang }}</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                            <td><a href="{% url 'main:profile' pk=player.player.pk %}">{{ player.player }}</a></td>
                            <td>{{ player.score }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="rating_women">
                <h3>Женщины</h3>
                <table>
                    <thead>
                    <tr style="background-color: #009688;">
                        <th>Место</th>
                        <th>Разряд</th>
                        <th>Спортсмен</th>
                        <th>Очки</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for player in woman %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            {% if not player.player.rang == 'nan' %}
                                <td>{{ player.player.rang }}</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                            <td><a href="{% url 'main:profile' pk=player.player.pk %}">{{ player.player }}</a></td>
                            <td>{{ player.score }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="rating_button">
            <a href="{% url 'rating:rating' %}">Весь рейтинг</a>
        </div>
    </div>
</section>

<footer>
    <div class="container">
        <div class="footer_logo">
            <a href="{% url 'main:index' %}">
                <img src="{% static 'img/logo.png' %}" alt="logo">
            </a>
        </div>
    </div>
</footer>

<script src="https://hlsbook.net/wp-content/examples/hls.min.js"></script>
<script>
    if (Hls.isSupported()) {
        let video = document.getElementById('video')
        let hls = new Hls()
        hls.loadSource('https://xn--90aa5bhn.xn--p1ai/static/video/out/master.m3u8')
        hls.attachMedia(video)
        hls.on(Hls.Events.MANIFEST_PARSED, function () {
            video.play();
        });
    }
</script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/protocols.html
{% extends 'layouts/basic.html' %}
{% load static %}
{% block links %}
    <link rel="stylesheet" href="{% static 'css/protocols.css' %}">
{% endblock %}
{% block title %}Протоколы{% endblock %}

{% block content %}
    <section class="section_protocols">
        <div class="container">
            <h1>Протоколы</h1>
            <p>2021</p>
            <a href="#">Протокол Президиума ФБ СПб 20.01.2020</a>
            <p>2020</p>
            <a href="#">Протокол Президиума ФБ СПб 19.03.2020</a>
            <a href="#">Протокол Президиума ФБ СПб 05.09.2020</a>
        </div>
    </section>
{% endblock %}

templates/statistics.html
{% extends 'layouts/basic.html' %}
{% load static %}
{% block links %}
    <link rel="stylesheet" href="{% static 'css/statistics_2.css' %}">
{% endblock %}
{% block title %}Статистика{% endblock %}

{% block content %}
    <section class="section_rating">
        <div class="container">
            <div class="rating_title">Статистика</div>
            <div class="rating_description">Рейтинг ведется на основе рейтинговых турниров проводимых федерацией
                согласно
                общим положениям. Результаты рейтинга используются для формирования сборной команды Санкт-Петербурга на
                следующий календарный год
            </div>
            <div class="rating_by_years">
                <div class="years">
                    <div class="years_list">
                        {% for year in years %}
                            {% if year.men or year.women %}
                                <h3 class="year" data-year="{{ year.year }}">{{ year.year }}</h3>
                                <div class="arrow-8"></div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% for year in years %}
                        {% if year.men or year.women %}
                            <div data-year="{{ year.year }}" class="rating">
                                <h4>Мужчины</h4>
                                <div class="tournament_result">
                                    <table>
                                        <thead>
                                        <tr style="background-color: #009688;">
                                            <th>Место</th>
                                            <th>Фамилия, Имя</th>
                                            <th>Звание, разряд</th>
                                            <th>Кол-во игр</th>
                                            <th>Худшая игра</th>
                                            <th>Лучшая игра</th>
                                            <th>Сумма кеглей</th>
                                            <th>Средний</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for player in year.men %}
                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td>
                                                    <a href="{% url 'main:profile' pk=player.name.id %}">{{ player.name.name }}</a>
                                                </td>
                                                <td>{% if player.name.rang != 'nan' %}
                                                    {{ player.name.rang }}{% endif %}</td>
                                                <td>{{ player.score }}</td>
                                                <td>{{ player.min }}</td>
                                                <td>{{ player.max }}</td>
                                                <td>{{ player.summ }}</td>
                                                <td>{{ player.mean }}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>

                                <h4>Женщины</h4>
                                <div class="tournament_result">
                                    <table>
                                        <thead>
                                        <tr style="background-color: #009688;">
                                            <th>Место</th>
                                            <th>Фамилия, Имя</th>
                                            <th>Звание, разряд</th>
                                            <th>Кол-во игр</th>
                                            <th>Худщая игра</th>
                                            <th>Лучшая игра</th>
                                            <th>Сумма кеглей</th>
                                            <th>Средний</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for player in year.women %}
                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td>
                                                    <a href="{% url 'main:profile' pk=player.name.id %}">{{ player.name.name }}</a>
                                                </td>
                                                <td>{% if player.name.rang != 'nan' %}
                                                    {{ player.name.rang }}{% endif %}</td>
                                                <td>{{ player.score }}</td>
                                                <td>{{ player.min }}</td>
                                                <td>{{ player.max }}</td>
                                                <td>{{ player.summ }}</td>
                                                <td>{{ player.mean }}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/tournament_list.html
{% extends 'layouts/basic.html' %}
{% load static %}
{% block links %}
    <link rel="stylesheet" href="{% static 'css/tournament_list_1.css' %}">
{% endblock %}
{% block title %}Отчеты по турнирам{% endblock %}

{% block content %}
    <section class="tournament_list_section">
        <div class="container">
            <div class="tournament_title">Отчеты</div>
            <div class="tournament_list">
                {% for post in tournaments %}
                    <figure class="baha1493">
                        <div {% if not post.news_image %}style="align-items: center; background-color: rgba(26, 48, 104, 0.9)"{% endif %}
                             class="image">
                            {% if post.report_image %}
                                <img src="{{ post.report_image.url }}" alt="ls-sample1"/>
                            {% else %}
                                <img width="100px" height="115px" src="{% static 'img/logo.png' %}" alt="">
                            {% endif %}
                        </div>
                        <figcaption>
                            <div class="date">
                                <span class="day">{{ post.date|date:'j' }}</span>
                                <span class="month_news">{{ post.date|date:'M' }}</span>
                            </div>
                            <h3>{{ post.name }}</h3>
                            <p>{{ post.short_description }}</p>
                            <div class="news_footer">
                                <div class="views"><i class="ion-eye"></i>{{ post.count }}</div>
                                {#                            <div class="comments"><i class="ion-chatboxes"></i>23</div>#}
                            </div>
                        </figcaption>
                        <a href="{% url 'tournaments:current_tournament' pk=post.pk %}"></a>
                    </figure>
                {% endfor %}
            </div>
            <div class="pagination">
                <ul class="pagination">
                    {% if previous_page_number %}
                        <li><a href="{% url 'tournaments:tournaments_list' %}?page={{ previous_page_number }}">«</a>
                        </li>
                    {% endif %}
                    {% if previous2 in page_range %}
                        <li><a href="{% url 'tournaments:tournaments_list' %}?page={{ previous2 }}">{{ previous2 }}</a>
                        </li>
                    {% endif %}
                    {% if previous_page_number %}
                        <li>
                            <a href="{% url 'tournaments:tournaments_list' %}?page={{ previous_page_number }}">{{ previous_page_number }}</a>
                        </li>
                    {% endif %}
                    <li><a class="active" href="#">{{ page }}</a></li>
                    {% if next_page_number %}
                        <li>
                            <a href="{% url 'tournaments:tournaments_list' %}?page={{ next_page_number }}">{{ next_page_number }}</a>
                        </li>
                    {% endif %}
                    {% if next2 in page_range %}
                        <li><a href="{% url 'tournaments:tournaments_list' %}?page={{ next2 }}">{{ next2 }}</a></li>
                    {% endif %}
                    {% if next_page_number %}
                        <li><a href="{% url 'tournaments:tournaments_list' %}?page={{ next_page_number }}">»</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </section>
{% endblock %}